# @package _global_

defaults:
  - _self_
  - model: cifar_resnet.yaml
  - dataset: streaming_cifar10.yaml
  - logger: null
  - optimizer: default.yaml
  - scheduler: default.yaml
  - callbacks:  
    - lr_monitor.yaml
    - speed_monitor.yaml
    - checkpoint.yaml
  - trainer: default.yaml
  - experiment: null

name: hydra-test-run





